version: '3'

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile

    container_name: lira-api-container

    volumes:
      - ./lira-api.log:/app/lira-api.log

    ports:
      - "8081:8080"

    expose:
      - 8080